"""
Report Generator - Creates markdown reports from analysis results
"""

from datetime import datetime
from pathlib import Path
from typing import Optional

import yaml
from jinja2 import BaseLoader, Environment, FileSystemLoader
from loguru import logger

from analyzer import AnalysisResult, StartupOpportunity
from database import Database

# Default report template
DEFAULT_TEMPLATE = """# HN Insights Report
**Generated**: {{ generated_at }}
**Insights Analyzed**: {{ result.total_insights_analyzed }}

---

## Executive Summary

{{ result.meta_insights }}

---

## Top Startup Opportunities

{% for opp in result.opportunities[:top_n] %}
### {{ loop.index }}. {{ opp.title }}

**Score**: {{ "%.1f"|format(opp.total_score) }}/10 | **Categories**: {{ opp.categories | join(", ") }}

{{ opp.description }}

#### Target User
{{ opp.target_user }}

#### Problem Statement
{{ opp.problem_statement }}

#### Existing Solutions
{% for sol in opp.existing_solutions %}
- {{ sol }}
{% endfor %}

#### Differentiation
{{ opp.differentiation }}

#### Evidence from HN
{% for evidence in opp.evidence[:5] %}
> {{ evidence }}
{% endfor %}

#### Opportunity Scores
| Metric | Score |
|--------|-------|
| Pain Intensity | {{ opp.scores.pain_intensity }}/10 |
| Frequency | {{ opp.scores.frequency }}/10 |
| Market Size | {{ opp.scores.market_size }}/10 |
| Monetization | {{ opp.scores.monetization }}/10 |
| Feasibility | {{ opp.scores.feasibility }}/10 |

#### Next Steps
{% for step in opp.next_steps %}
1. {{ step }}
{% endfor %}

---

{% endfor %}

## Emerging Trends

{% for trend in result.trends %}
### {{ trend.trend }}

**Supporting Signals**:
{% for signal in trend.supporting_signals %}
- {{ signal }}
{% endfor %}

{% endfor %}

---

## Insights Breakdown

### By Category
| Category | Count |
|----------|-------|
{% for cat, count in result.categories_breakdown.items() %}
| {{ cat | replace("_", " ") | title }} | {{ count }} |
{% endfor %}

### By Type
| Insight Type | Count |
|--------------|-------|
{% for type, count in result.insight_types_breakdown.items() %}
| {{ type | replace("_", " ") | title }} | {{ count }} |
{% endfor %}

---

*Generated by HN Insights Scraper*
"""


DAILY_DIGEST_TEMPLATE = """# HN Daily Insights Digest
**Date**: {{ date }}
**Stories Processed**: {{ stats.stories }}
**Insights Extracted**: {{ stats.insights }}

---

## Today's Top Opportunities

{% for opp in opportunities[:5] %}
### {{ opp.title }} ({{ "%.1f"|format(opp.total_score) }}/10)

{{ opp.description[:300] }}...

**Target**: {{ opp.target_user }}

**Key Evidence**:
{% for e in opp.evidence[:2] %}
> {{ e }}
{% endfor %}

---

{% endfor %}

## Quick Stats

- **Pain Points Found**: {{ type_counts.get('pain_point', 0) }}
- **Feature Requests**: {{ type_counts.get('feature_request', 0) }}
- **Market Gaps**: {{ type_counts.get('market_gap', 0) }}
- **Willingness to Pay Signals**: {{ type_counts.get('willingness_to_pay', 0) }}

## Top Categories Today

{% for cat, count in categories[:5] %}
- **{{ cat | replace("_", " ") | title }}**: {{ count }} insights
{% endfor %}

---

*View full report for detailed analysis*
"""


class ReportGenerator:
    """
    Generates markdown reports from analysis results
    """

    def __init__(
        self,
        output_dir: str = "reports",
        config_path: str = "config.yaml",
    ):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Load config
        self.config = {}
        if Path(config_path).exists():
            with open(config_path) as f:
                self.config = yaml.safe_load(f)

        report_config = self.config.get("reports", {})
        self.top_n = report_config.get("top_insights", 20)

        # Setup Jinja2 environment
        self.env = Environment(loader=BaseLoader())

    def render_template(
        self,
        template_str: str,
        **kwargs,
    ) -> str:
        """Render a Jinja2 template string"""
        template = self.env.from_string(template_str)
        return template.render(**kwargs)

    def generate_full_report(
        self,
        result: AnalysisResult,
        filename: Optional[str] = None,
    ) -> Path:
        """
        Generate a full analysis report
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"insights_report_{timestamp}.md"

        content = self.render_template(
            DEFAULT_TEMPLATE,
            result=result,
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            top_n=self.top_n,
        )

        output_path = self.output_dir / filename
        output_path.write_text(content)

        logger.info(f"Generated full report: {output_path}")
        return output_path

    def generate_daily_digest(
        self,
        result: AnalysisResult,
        db: Database,
        filename: Optional[str] = None,
    ) -> Path:
        """
        Generate a concise daily digest
        """
        if filename is None:
            date_str = datetime.now().strftime("%Y%m%d")
            filename = f"daily_digest_{date_str}.md"

        # Get stats
        stats = db.get_stats()

        # Sort categories by count
        categories = sorted(
            result.categories_breakdown.items(),
            key=lambda x: x[1],
            reverse=True,
        )

        content = self.render_template(
            DAILY_DIGEST_TEMPLATE,
            date=datetime.now().strftime("%Y-%m-%d"),
            stats=stats,
            opportunities=result.opportunities,
            type_counts=result.insight_types_breakdown,
            categories=categories,
        )

        output_path = self.output_dir / filename
        output_path.write_text(content)

        logger.info(f"Generated daily digest: {output_path}")
        return output_path

    def generate_opportunity_card(
        self,
        opportunity: StartupOpportunity,
    ) -> str:
        """
        Generate a single opportunity as markdown
        """
        template = """## {{ opp.title }}

**Overall Score**: {{ "%.1f"|format(opp.total_score) }}/10

### The Opportunity
{{ opp.description }}

### Target User
{{ opp.target_user }}

### Problem
{{ opp.problem_statement }}

### Why Now?
{{ opp.differentiation }}

### Evidence
{% for e in opp.evidence %}
> {{ e }}
{% endfor %}

### Scores Breakdown
- Pain Intensity: {{ opp.scores.pain_intensity }}/10
- Frequency: {{ opp.scores.frequency }}/10
- Market Size: {{ opp.scores.market_size }}/10
- Monetization Potential: {{ opp.scores.monetization }}/10
- Feasibility: {{ opp.scores.feasibility }}/10

### Validation Steps
{% for step in opp.next_steps %}
{{ loop.index }}. {{ step }}
{% endfor %}
"""
        return self.render_template(template, opp=opportunity)

    def generate_json_export(
        self,
        result: AnalysisResult,
        filename: Optional[str] = None,
    ) -> Path:
        """
        Export analysis results as JSON
        """
        import json

        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"insights_export_{timestamp}.json"

        # Convert to dict
        data = {
            "generated_at": datetime.now().isoformat(),
            "total_insights": result.total_insights_analyzed,
            "opportunities": [
                {
                    "title": opp.title,
                    "description": opp.description,
                    "target_user": opp.target_user,
                    "problem_statement": opp.problem_statement,
                    "existing_solutions": opp.existing_solutions,
                    "differentiation": opp.differentiation,
                    "evidence": opp.evidence,
                    "scores": {
                        "pain_intensity": opp.scores.pain_intensity,
                        "frequency": opp.scores.frequency,
                        "market_size": opp.scores.market_size,
                        "monetization": opp.scores.monetization,
                        "feasibility": opp.scores.feasibility,
                        "total": opp.total_score,
                    },
                    "categories": opp.categories,
                    "next_steps": opp.next_steps,
                }
                for opp in result.opportunities
            ],
            "trends": [
                {
                    "trend": t.trend,
                    "signals": t.supporting_signals,
                }
                for t in result.trends
            ],
            "meta_insights": result.meta_insights,
            "breakdowns": {
                "by_category": result.categories_breakdown,
                "by_type": result.insight_types_breakdown,
            },
        }

        output_path = self.output_dir / filename
        output_path.write_text(json.dumps(data, indent=2))

        logger.info(f"Generated JSON export: {output_path}")
        return output_path


def print_opportunity_to_console(opp: StartupOpportunity):
    """Print a single opportunity to console with rich formatting"""
    from rich.console import Console
    from rich.markdown import Markdown
    from rich.panel import Panel
    from rich.table import Table

    console = Console()

    # Title panel
    console.print(
        Panel(
            f"[bold]{opp.title}[/bold]\n"
            f"Score: [green]{opp.total_score:.1f}/10[/green] | "
            f"Categories: {', '.join(opp.categories)}",
            title="Opportunity",
            border_style="blue",
        )
    )

    # Description
    console.print(f"\n[bold]Description:[/bold]\n{opp.description}\n")

    # Target user
    console.print(f"[bold]Target User:[/bold] {opp.target_user}\n")

    # Problem
    console.print(f"[bold]Problem:[/bold] {opp.problem_statement}\n")

    # Scores table
    table = Table(title="Opportunity Scores")
    table.add_column("Metric", style="cyan")
    table.add_column("Score", justify="right")

    table.add_row("Pain Intensity", f"{opp.scores.pain_intensity}/10")
    table.add_row("Frequency", f"{opp.scores.frequency}/10")
    table.add_row("Market Size", f"{opp.scores.market_size}/10")
    table.add_row("Monetization", f"{opp.scores.monetization}/10")
    table.add_row("Feasibility", f"{opp.scores.feasibility}/10")
    table.add_row("[bold]Total[/bold]", f"[bold]{opp.total_score:.1f}/10[/bold]")

    console.print(table)

    # Evidence
    console.print("\n[bold]Evidence from HN:[/bold]")
    for e in opp.evidence[:3]:
        console.print(f"  > {e}")

    console.print()


if __name__ == "__main__":
    print("Report Generator module loaded successfully")
